FROM php:8.5-fpm-alpine
RUN apk update
RUN apk add gmp-dev libpq-dev
RUN docker-php-ext-install pdo_mysql pdo_pgsql gmp
COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_HOME /app/.composer
