FROM php:7.4-fpm-alpine
RUN apk update && apk add gmp-dev
RUN docker-php-ext-install pdo_mysql gmp
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
RUN mkdir -p /home/composer/.composer && chmod 0777 /home/composer/.composer
ENV COMPOSER_HOME /home/composer/.composer
