<?php

declare(strict_types=1);

namespace EveSrp\Migrations\PostgreSQL;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * @noinspection PhpUnused
 */
final class Version20240721183445 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE actions ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE divisions ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE external_groups ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE modifiers ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE permissions ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE permissions ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE divisions ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE modifiers ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE actions ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE external_groups ALTER id DROP IDENTITY');
    }
}
